export const partnerBrandLogoById: Record<string, string> = {
  "brand-al-fakher": "/logos/brands/al-fakher.webp",
  "brand-dr-vapes": "/logos/brands/dr-vapes.webp",
  "brand-geekvape": "/logos/brands/geekvape.webp",
  "brand-ivg": "/logos/brands/ivg.webp",
  "brand-lostvape": "/logos/brands/lostvape.webp",
  "brand-nasty": "/logos/brands/nasty.webp",
  "brand-nexa": "/logos/brands/nexa.webp",
  "brand-oxbar": "/logos/brands/oxbar.webp",
  "brand-pod-salt": "/logos/brands/pod-salt.webp",
  "brand-ripe-vapes": "/logos/brands/ripe-vapes.webp",
  "brand-smok": "/logos/brands/smok.webp",
  "brand-uwell": "/logos/brands/uwell.webp",
  "brand-vaporesso": "/logos/brands/vaporesso.webp",
  "brand-vgod": "/logos/brands/vgod.webp",
  "brand-voopoo": "/logos/brands/voopoo.webp",
  "brand-vozol": "/logos/brands/vozol.webp",
  "brand-waka": "/logos/brands/waka.webp",
};
